language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ymykai/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ymykai/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-138618234684"
    bucket_pass: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY